CREATE TABLE STG_OPP_ATLAS AS
SELECT *
FROM IN_OPP_ATLAS;

ALTER TABLE STG_OPP_ATLAS DROP _smart_source_bucket;
ALTER TABLE STG_OPP_ATLAS DROP _smart_source_file;
ALTER TABLE STG_OPP_ATLAS DROP _smart_source_lineno;
ALTER TABLE STG_OPP_ATLAS DROP name;