CREATE TABLE STG_ZILLOW_IDX AS
SELECT *
FROM IN_ZILLOW_IDX;

ALTER TABLE STG_ZILLOW_IDX DROP regiontype;
ALTER TABLE STG_ZILLOW_IDX DROP regionname;
ALTER TABLE STG_ZILLOW_IDX DROP countyname;
ALTER TABLE STG_ZILLOW_IDX DROP sizerank;
ALTER TABLE STG_ZILLOW_IDX DROP state;
ALTER TABLE STG_ZILLOW_IDX DROP statename;
ALTER TABLE STG_ZILLOW_IDX DROP metro;
ALTER TABLE STG_ZILLOW_IDX DROP _smart_source_bucket;
ALTER TABLE STG_ZILLOW_IDX DROP _smart_source_file;
ALTER TABLE STG_ZILLOW_IDX DROP _smart_source_lineno;
ALTER TABLE STG_ZILLOW_IDX DROP city;